# -*- coding: utf-8 -*-

from . import models
from . import utils

# Version management - 'best practice' from
# https://smarie.github.io/python-getversion/#package-versioning-best-practices
try:
    # Distribution mode: use the file generated by setuptools_scm in the wheel
    from ._version import version as __version__
except ImportError:
    # Source mode: use git to know the version
    from setuptools_scm import get_version as _gv
    from os import path as _path
    __version__ = _gv(_path.join(_path.dirname(__file__), _path.pardir))

__all__ = ['models', 'utils', '__version__']
