# -*- coding: utf-8 -*-

"""Single-Objective Generative Adversarial Active Learning.
Part of the codes are adapted from
https://github.com/leibinghe/GAAL-based-outlier-detection
"""
# Author: Sihan Chen <schen976@usc.edu>, Tiankai Yang <tiankaiy@usc.edu>
# License: BSD 2 clause

import math

try:
    import torch
    import torch.nn as nn
except ImportError as e:
    raise ImportError(
        "PyTorch is required for GAAL models. Please install it with "
        "`pip install pyod[torch]` or `pip install torch`."
    ) from e

from .base_dl import BaseDeepLearningDetector
from ..utils.torch_utility import LinearBlock, get_optimizer_by_name


class SO_GAAL(BaseDeepLearningDetector):
    """Single-Objective Generative Adversarial Active Learning.

    SO-GAAL directly generates informative potential outliers to assist the
    classifier in describing a boundary that can separate outliers from normal
    data effectively. Moreover, to prevent the generator from falling into the
    mode collapsing problem, the network structure of SO-GAAL is expanded from
    a single generator (SO-GAAL) to multiple generators with different
    objectives (MO-GAAL) to generate a reasonable reference distribution for
    the whole dataset.

    Parameters
    ----------
    contamination : float in (0., 0.5), optional (default=0.1)
        The amount of contamination of the data set, i.e.
        the proportion of outliers in the data set. Used when fitting to
        define the threshold on the decision function.

    preprocessing : bool, optional (default=True)
        If True, apply standardization on the data.

    epoch_num : int, optional (default=100)
        The number of epochs of training. Training stops early, after
        ``epoch_num // 3`` epochs, once the generator has converged.

    criterion_name : str, optional (default='bce')
        Name of the loss used to train the discriminator.

    device : str, torch.device or None, optional (default=None)
        Device used for computation. If None, use the PyTorch default device.

    random_state : int, optional (default=42)
        Random seed used to make the results reproducible.

    use_compile : bool, optional (default=False)
        If True, compile the model with ``torch.compile`` before training.
        Requires PyTorch 2.0 or later; ignored on older versions.

    compile_mode : str, optional (default='default')
        Compilation mode forwarded to ``torch.compile`` when ``use_compile``
        is True.

    verbose : int, optional (default=1)
        Verbosity mode.
        - 0 = silent
        - 1 = progress bar
        - 2 = one line per epoch

    lr_d : float, optional (default=0.01)
        The learning rate of the discriminator.

    lr_g : float, optional (default=0.0001)
        The learning rate of the generator.

    momentum : float, optional (default=0.9)
        The momentum parameter for SGD.

    Attributes
    ----------
    decision_scores_ : numpy array of shape (n_samples,)
        The outlier scores of the training data.
        The higher, the more abnormal. Outliers tend to have higher
        scores. This value is available once the detector is fitted.

    threshold_ : float
        The threshold is based on ``contamination``. It is the
        ``n_samples * contamination`` most abnormal samples in
        ``decision_scores_``. The threshold is calculated for generating
        binary outlier labels.

    labels_ : numpy array of shape (n_samples,)
        The binary labels of the training data. 0 stands for inliers
        and 1 for outliers/anomalies. It is generated by applying
        ``threshold_`` on ``decision_scores_``.
    """

    def __init__(self, contamination=0.1, preprocessing=True,
                 epoch_num=100,
                 criterion_name='bce',
                 device=None, random_state=42,
                 use_compile=False, compile_mode='default',
                 verbose=1,
                 lr_d=0.01, lr_g=0.0001, momentum=0.9):
        super(SO_GAAL, self).__init__(contamination=contamination,
                                      preprocessing=preprocessing,
                                      epoch_num=epoch_num,
                                      criterion_name=criterion_name,
                                      device=device, random_state=random_state,
                                      use_compile=use_compile,
                                      compile_mode=compile_mode,
                                      verbose=verbose)
        self.lr_d = lr_d
        self.lr_g = lr_g
        self.momentum = momentum
        self.stop_epoch_num = self.epoch_num // 3
        if self.stop_epoch_num < 1:
            self.stop_epoch_num = 1

    def build_model(self):
        self.generator = Generator(self.feature_size)
        self.discriminator = Discriminator(self.feature_size, self.data_num)

    def training_prepare(self):
        # decide if the generator training should stop
        self.stop_flag = False

        self.batch_size = min(500, self.data_num)

        self.generator.to(self.device)
        self.discriminator.to(self.device)

        self.optimizer_d = get_optimizer_by_name(self.discriminator, 'sgd',
                                                 lr=self.lr_d,
                                                 sgd_momentum=self.momentum)
        self.optimizer_g = get_optimizer_by_name(self.generator, 'sgd',
                                                 lr=self.lr_g,
                                                 sgd_momentum=self.momentum)

        if self.use_compile:
            self.generator = torch.compile(model=self.generator,
                                           mode=self.compile_mode)
            self.discriminator = torch.compile(model=self.discriminator,
                                               mode=self.compile_mode)
            print('Model compiled.')

    def evaluating_prepare(self):
        self.generator.eval()
        self.discriminator.eval()

        self.generator.train()
        self.discriminator.train()

    def training_forward(self, batch_data):
        batch_data = batch_data.to(self.device)
        batch_data_num = batch_data.size(0)
        self.optimizer_d.zero_grad()

        # Draw samples from the uniform distribution
        noise = torch.rand(batch_data_num, self.feature_size,
                           device=self.device)

        # Train Discriminator
        generated_data = self.generator(noise)

        real_labels = torch.ones(batch_data_num, 1, device=self.device)
        fake_labels = torch.zeros(batch_data_num, 1, device=self.device)

        real_outputs = self.discriminator(batch_data)
        fake_outputs = self.discriminator(generated_data)

        loss_d_real = self.criterion(real_outputs, real_labels)
        loss_d_fake = self.criterion(fake_outputs, fake_labels)

        loss_d = loss_d_real + loss_d_fake
        loss_d.backward()
        self.optimizer_d.step()

        # Train Generator
        if not self.stop_flag:
            self.optimizer_g.zero_grad()
            trick_labels = torch.ones(batch_data_num, 1, device=self.device)
            loss_g = self.criterion(self.discriminator(noise), trick_labels)
            loss_g.backward()
            self.optimizer_g.step()
        else:
            loss_g = torch.tensor(0.0)

        return loss_d.item(), loss_g.item()

    def epoch_update(self):
        if self.epoch_num >= self.stop_epoch_num:
            self.stop_flag = True

    def evaluating_forward(self, batch_data):
        batch_data = batch_data.to(self.device)
        score = self.discriminator(batch_data).cpu().numpy().ravel()
        return score


class Generator(nn.Module):
    def __init__(self, feature_size):
        super(Generator, self).__init__()
        self.block1 = LinearBlock(feature_size, feature_size,
                                  activation_name='relu', init_type="eye")
        self.block2 = LinearBlock(feature_size, feature_size,
                                  activation_name='relu', init_type="eye")

    def forward(self, x):
        x = self.block1(x)
        x = self.block2(x)
        return x


class Discriminator(nn.Module):
    def __init__(self, feature_size, data_num):
        super(Discriminator, self).__init__()
        intermidiate_size = math.ceil(math.sqrt(data_num))
        self.block1 = LinearBlock(feature_size, intermidiate_size,
                                  activation_name='relu',
                                  init_type="kaiming_normal",
                                  init_params={'kaiming_mode': 'fan_in',
                                               'kaiming_nonlinearity': 'relu'})
        self.block2 = LinearBlock(intermidiate_size, 1,
                                  activation_name='sigmoid',
                                  init_type="kaiming_normal",
                                  init_params={'kaiming_mode': 'fan_in',
                                               'kaiming_nonlinearity': 'sigmoid'})

    def forward(self, x):
        x = self.block1(x)
        x = self.block2(x)
        return x
